version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: dietwise-postgres
    environment:
      POSTGRES_DB: dietwise
      POSTGRES_USER: dietwise_user
      POSTGRES_PASSWORD: your_secure_password_here
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dietwise-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dietwise_user -d dietwise"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: dietwise-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: your_secure_password_here
      MONGO_INITDB_DATABASE: dietwise
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - dietwise-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: dietwise-redis
    command: redis-server --requirepass your_redis_password_here
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - dietwise-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dietwise-backend
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://dietwise_user:your_secure_password_here@postgres:5432/dietwise
      MONGODB_URI: mongodb://admin:your_secure_password_here@mongodb:27017/dietwise?authSource=admin
      REDIS_URL: redis://:your_redis_password_here@redis:6379
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - dietwise-network
    restart: unless-stopped

  # Frontend (for development)
  frontend:
    image: node:20-alpine
    container_name: dietwise-frontend
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/backend/node_modules
    command: npm run dev
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3001/api/v1
    networks:
      - dietwise-network

volumes:
  postgres_data:
  mongodb_data:
  redis_data:

networks:
  dietwise-network:
    driver: bridge