[build]
  command = "npm run build:production"
  publish = "dist"
  functions = "netlify/functions"

# Fix JavaScript module MIME types
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
